theme: jekyll-theme-minimal
title: [A collection of words/pictures/projects that have been produced with the help of David Evans]
description: [:copyright: :books: :sagittarius: :speech_balloon: :deciduous_tree: :1st_place_medal: :bike: :mountain_snow:]
